# Authentication errors
AUTH_REQUIRED = "AUTH_REQUIRED"
SPOTIFY_UNAUTHORIZED = "SPOTIFY_UNAUTHORIZED"
TOKEN_EXPIRED = "TOKEN_EXPIRED"

# Validation errors
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_PARAMETER = "INVALID_PARAMETER"

# API errors
SPOTIFY_API_ERROR = "SPOTIFY_API_ERROR"
RATE_LIMITED = "RATE_LIMITED"
NOT_FOUND = "NOT_FOUND"

# Server errors
INTERNAL_ERROR = "INTERNAL_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
